using NLog;
using NLog.Targets;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace NlogBatchInsert
{
    class Program
    {
        const int threadCount = 10; // Test threads number
        const int messageCount = 100; // Message generated by each thread


        static void Main(string[] args)
        {
            // Register the customized target at the very beginning
            Target.Register("BatchInsertDbTarget", typeof(BatchInsertDbTarget));

            LoggingTest();

            Console.WriteLine("Press any key to continue...");
            Console.ReadKey();
        }

        static void LoggingTest()
        {
            Thread[] threads = new Thread[threadCount];

            for (int i = 0; i < threadCount; ++i)
            {
                threads[i] = new Thread(new ParameterizedThreadStart(ThreadLogging));
                threads[i].Start(i);
            }

            for (int i = 0; i < threadCount; ++i)
            {
                threads[i].Join();
            }
        }

        static void ThreadLogging(object threadId)
        {
            Logger logger = LogManager.GetLogger("logger");

            // Example to set thread-related context fields
            MappedDiagnosticsLogicalContext.Set("traceid", "Trace " + threadId.ToString());

            for (int i = 0; i < messageCount; ++i)
            {
                logger.Debug("Message " + i.ToString());
            }
        }
    }
}
